/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ETakipRouteImport } from './routes/e-takip'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as HizmetlerRouteImport } from './routes/hizmetler'
import { Route as IkRouteImport } from './routes/ik'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as SektorelAkisRouteImport } from './routes/sektorel-akis'
import { Route as UygulamalarRouteImport } from './routes/uygulamalar'
import { Route as ApiPublicAbonelikIptalRouteImport } from './routes/api/public/abonelik-iptal'
import { Route as ApiPublicHooksAnnouncementPublishedRouteImport } from './routes/api/public/hooks/announcement-published'
import { Route as ApiPublicHooksWeeklyApplicationsRouteImport } from './routes/api/public/hooks/weekly-applications'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ETakipRoute = ETakipRouteImport.update({
  id: '/e-takip',
  path: '/e-takip',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerRoute = HizmetlerRouteImport.update({
  id: '/hizmetler',
  path: '/hizmetler',
  getParentRoute: () => rootRouteImport,
} as any)
const IkRoute = IkRouteImport.update({
  id: '/ik',
  path: '/ik',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const SektorelAkisRoute = SektorelAkisRouteImport.update({
  id: '/sektorel-akis',
  path: '/sektorel-akis',
  getParentRoute: () => rootRouteImport,
} as any)
const UygulamalarRoute = UygulamalarRouteImport.update({
  id: '/uygulamalar',
  path: '/uygulamalar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAbonelikIptalRoute = ApiPublicAbonelikIptalRouteImport.update({
  id: '/api/public/abonelik-iptal',
  path: '/api/public/abonelik-iptal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAnnouncementPublishedRoute =
  ApiPublicHooksAnnouncementPublishedRouteImport.update({
    id: '/api/public/hooks/announcement-published',
    path: '/api/public/hooks/announcement-published',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyApplicationsRoute =
  ApiPublicHooksWeeklyApplicationsRouteImport.update({
    id: '/api/public/hooks/weekly-applications',
    path: '/api/public/hooks/weekly-applications',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e-takip': typeof ETakipRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/ik': typeof IkRoute
  '/iletisim': typeof IletisimRoute
  '/sektorel-akis': typeof SektorelAkisRoute
  '/uygulamalar': typeof UygulamalarRoute
  '/api/public/abonelik-iptal': typeof ApiPublicAbonelikIptalRoute
  '/api/public/hooks/announcement-published': typeof ApiPublicHooksAnnouncementPublishedRoute
  '/api/public/hooks/weekly-applications': typeof ApiPublicHooksWeeklyApplicationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e-takip': typeof ETakipRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/ik': typeof IkRoute
  '/iletisim': typeof IletisimRoute
  '/sektorel-akis': typeof SektorelAkisRoute
  '/uygulamalar': typeof UygulamalarRoute
  '/api/public/abonelik-iptal': typeof ApiPublicAbonelikIptalRoute
  '/api/public/hooks/announcement-published': typeof ApiPublicHooksAnnouncementPublishedRoute
  '/api/public/hooks/weekly-applications': typeof ApiPublicHooksWeeklyApplicationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/e-takip': typeof ETakipRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/ik': typeof IkRoute
  '/iletisim': typeof IletisimRoute
  '/sektorel-akis': typeof SektorelAkisRoute
  '/uygulamalar': typeof UygulamalarRoute
  '/api/public/abonelik-iptal': typeof ApiPublicAbonelikIptalRoute
  '/api/public/hooks/announcement-published': typeof ApiPublicHooksAnnouncementPublishedRoute
  '/api/public/hooks/weekly-applications': typeof ApiPublicHooksWeeklyApplicationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/e-takip'
    | '/hakkimizda'
    | '/hizmetler'
    | '/ik'
    | '/iletisim'
    | '/sektorel-akis'
    | '/uygulamalar'
    | '/api/public/abonelik-iptal'
    | '/api/public/hooks/announcement-published'
    | '/api/public/hooks/weekly-applications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/e-takip'
    | '/hakkimizda'
    | '/hizmetler'
    | '/ik'
    | '/iletisim'
    | '/sektorel-akis'
    | '/uygulamalar'
    | '/api/public/abonelik-iptal'
    | '/api/public/hooks/announcement-published'
    | '/api/public/hooks/weekly-applications'
  id:
    | '__root__'
    | '/'
    | '/e-takip'
    | '/hakkimizda'
    | '/hizmetler'
    | '/ik'
    | '/iletisim'
    | '/sektorel-akis'
    | '/uygulamalar'
    | '/api/public/abonelik-iptal'
    | '/api/public/hooks/announcement-published'
    | '/api/public/hooks/weekly-applications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ETakipRoute: typeof ETakipRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  HizmetlerRoute: typeof HizmetlerRoute
  IkRoute: typeof IkRoute
  IletisimRoute: typeof IletisimRoute
  SektorelAkisRoute: typeof SektorelAkisRoute
  UygulamalarRoute: typeof UygulamalarRoute
  ApiPublicAbonelikIptalRoute: typeof ApiPublicAbonelikIptalRoute
  ApiPublicHooksAnnouncementPublishedRoute: typeof ApiPublicHooksAnnouncementPublishedRoute
  ApiPublicHooksWeeklyApplicationsRoute: typeof ApiPublicHooksWeeklyApplicationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-takip': {
      id: '/e-takip'
      path: '/e-takip'
      fullPath: '/e-takip'
      preLoaderRoute: typeof ETakipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler': {
      id: '/hizmetler'
      path: '/hizmetler'
      fullPath: '/hizmetler'
      preLoaderRoute: typeof HizmetlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ik': {
      id: '/ik'
      path: '/ik'
      fullPath: '/ik'
      preLoaderRoute: typeof IkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sektorel-akis': {
      id: '/sektorel-akis'
      path: '/sektorel-akis'
      fullPath: '/sektorel-akis'
      preLoaderRoute: typeof SektorelAkisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uygulamalar': {
      id: '/uygulamalar'
      path: '/uygulamalar'
      fullPath: '/uygulamalar'
      preLoaderRoute: typeof UygulamalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/abonelik-iptal': {
      id: '/api/public/abonelik-iptal'
      path: '/api/public/abonelik-iptal'
      fullPath: '/api/public/abonelik-iptal'
      preLoaderRoute: typeof ApiPublicAbonelikIptalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/announcement-published': {
      id: '/api/public/hooks/announcement-published'
      path: '/api/public/hooks/announcement-published'
      fullPath: '/api/public/hooks/announcement-published'
      preLoaderRoute: typeof ApiPublicHooksAnnouncementPublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-applications': {
      id: '/api/public/hooks/weekly-applications'
      path: '/api/public/hooks/weekly-applications'
      fullPath: '/api/public/hooks/weekly-applications'
      preLoaderRoute: typeof ApiPublicHooksWeeklyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ETakipRoute: ETakipRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  HizmetlerRoute: HizmetlerRoute,
  IkRoute: IkRoute,
  IletisimRoute: IletisimRoute,
  SektorelAkisRoute: SektorelAkisRoute,
  UygulamalarRoute: UygulamalarRoute,
  ApiPublicAbonelikIptalRoute: ApiPublicAbonelikIptalRoute,
  ApiPublicHooksAnnouncementPublishedRoute:
    ApiPublicHooksAnnouncementPublishedRoute,
  ApiPublicHooksWeeklyApplicationsRoute: ApiPublicHooksWeeklyApplicationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
